# Generated by Django 2.2.10 on 2020-05-01 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Doença')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo do Paciente')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Idade do Paciente')),
                ('survival', models.IntegerField(blank=True, null=True, verbose_name='Paciente Sobreviveu')),
                ('original_image', models.ImageField(unique=True, upload_to='images/origin', verbose_name='Imagem')),
                ('resized_image', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Imagem Modificada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Disease', to='covid19.DiseaseType')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_source', models.CharField(max_length=60, unique=True, verbose_name='Descição da Fonte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_image_type', models.CharField(max_length=100, unique=True, verbose_name='Descição do Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_reason', models.CharField(max_length=255, unique=True, verbose_name='Descrição da Razão de Recusa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_view_type', models.CharField(max_length=45, unique=True, verbose_name='Tipo de Visualização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageApproved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0, verbose_name='Válido')),
                ('obs', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image', to='covid19.Image')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reason', to='covid19.Reason', verbose_name='Razão/Motivo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserApprove', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImageSource', to='covid19.ImageSource'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImageType', to='covid19.ImageType'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='image',
            name='view_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ViewType', to='covid19.ViewType'),
        ),
    ]
