# Generated by Django 2.2.10 on 2020-05-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AlterField(
            model_name='image',
            name='resized_image',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True, unique=True, verbose_name='Imagem Modificada'),
        ),
    ]
